server:
  port: 80

spring:
  application:
    name: gateway-zuul


eureka:
  instance:
    # 每间隔2s。选项注册中心发送一次心跳。证明客户端存活
    lease-renewal-interval-in-seconds: 2
    # 如果我10s之内没有向注册中心发送心跳，注册中心可以判断我故障，将我剔除
    lease-expiration-duration-in-seconds: 10
    # 服务实例以IP作为链接，而不是取机器名
    prefer-ip-address: true
    instance-id: gateway-zuul-80

  client:
    service-url:
      # 注册中心地址
      defaultZone: http://eureka8761:8761/eureka,http://eureka8762:8762/eureka
#    fetch-registry: true


hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds:  32000
#          strategy: Semaphore

ribbon:
  ReadTimeout: 15000  # 如果不配置，默认 1s, hystrix 会用该配置和 hystrix.command.default.execution.isolation.timeoutInMilliseconds 比价，谁小谁生效。
  ConnnectTimeout: 3000
  eureka:
    enabled: true
zuul:
  routes:
    consumer9002: /consumer/**
    provider: /provider/**
  # 禁止以服务名访问
  ignored-services: "*"
  # 前端访问时需加上前缀，和 servlet.context-path 类似
  prefix: /kauna
  # 不给匹配此模式的路由，当出现此路径是，会访问不到
  ignored-patterns: /**/feign/**

  # 禁用 myZuulFilter 过滤器
#  MyZuulFilter:
#    pre:
#      disable: true
  # 禁用 DebugFilter 过滤器
  DebugFilter:
    pre:
      disable: true


#zuul:
#   ignoredServices: '*'
#   host:
#      time-to-live: -1
#      connect-timeout-millis: 5000
#      max-per-route-connections: 10000
#      max-total-connections: 5000
#      socket-timeout-millis: 60000
#   semaphore:
#      max-semaphores: 500