server:
  port: 9000
#  servlet:
#    context-path: /provider
eureka:
  instance:
    # 每间隔2s。选项注册中心发送一次心跳。证明客户端存活
    lease-renewal-interval-in-seconds: 2
    # 如果我10s之内没有向注册中心发送心跳，注册中心可以判断我故障，将我剔除
    lease-expiration-duration-in-seconds: 10
    # 服务实例以IP作为链接，而不是取机器名
    prefer-ip-address: true
    # id 必须要唯一
    instance-id: provider-service-9000

  client:
    fetch-registry: true
    service-url:
      # 注册中心地址
#      defaultZone: http://eureka8761:8761/eureka,http://eureka8762:8762/eureka
      defaultZone: http://eureka8761:8761/eureka,http://eureka8762:8762/eureka


spring:
  application:
    name: provider
  zipkin:
    base-url: http://localhost:9410
    sender:
      type: web   # http 基于什么类型将打点数据发送给 zipkin-server

  sleuth:
    sampler:
     # request 采样数量，默认是 0.1，因为分布式系统中书库量会很大。测试环境数据量少，设置为全部采样
      probability: 1.0
