server:
  port: 9100
#  servlet:
#    context-path: /provider
eureka:
  instance:
    # 每间隔2s。选项注册中心发送一次心跳。证明客户端存活
    lease-renewal-interval-in-seconds: 2
    # 如果我10s之内没有向注册中心发送心跳，注册中心可以判断我故障，将我剔除
    lease-expiration-duration-in-seconds: 10
    # 服务实例以IP作为链接，而不是取机器名
    prefer-ip-address: true
    instance-id: provider-service-9100

  client:
    service-url:
      # 注册中心地址
#      defaultZone: http://eureka8761:8761/eureka,http://eureka8762:8762/eureka
      defaultZone: http://eureka8761:8761/eureka,http://eureka8762:8762/eureka

spring:
  application:
    name: provider